use_frameworks!

platform :ios, '9.0'

target 'react-native-async-storage_Example' do
  pod 'react-native-async-storage', :path => '../'

  target 'react-native-async-storage_Tests' do
    inherit! :search_paths

    
  end
end
